services:
  persistence:
    build: .
    image: notebookum-persistence:v1.0.0
    restart: unless-stopped
    env_file: .env
    deploy:
      replicas: 2
    networks:
      notebookum-network:
        aliases:
          - persistence-java.universidad.localhost
    environment:
      - CONSUL_URL=http://consul:8500

networks:
  notebookum-network:
    external: true