spring:
  application:
    name: persistence
  datasource:
    url: jdbc:postgresql://${DB_WRITE_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notebookum_db}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    hikari:
      pool-name: persistence-pool
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      test-query: SELECT 1
      initialization-fail-timeout: 10000
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  data:
    jpa:
      hibernate:
        ddl-auto: ${DDL_AUTO:validate}
      show-sql: ${SHOW_SQL:true}
      properties:
        hibernate:
          format_sql: ${FORMAT_SQL:false}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
